// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAv-0lGRUr9KEqoUVLPmQ_XbFSapY6_RlE',
    appId: '1:797974287154:web:6de1cb38c65e346eacbd2b',
    messagingSenderId: '797974287154',
    projectId: 'ecommerce-fbf9c',
    authDomain: 'ecommerce-fbf9c.firebaseapp.com',
    storageBucket: 'ecommerce-fbf9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRhMkSBoxAgWuqGLYF1oIFNyrFfaWsRUA',
    appId: '1:797974287154:android:ed8993be46f81fbdacbd2b',
    messagingSenderId: '797974287154',
    projectId: 'ecommerce-fbf9c',
    storageBucket: 'ecommerce-fbf9c.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYpNZVcPd4_-JrhYOB31dZb26XcgPKT6Q',
    appId: '1:797974287154:ios:ca2928bd15bc0bb6acbd2b',
    messagingSenderId: '797974287154',
    projectId: 'ecommerce-fbf9c',
    storageBucket: 'ecommerce-fbf9c.appspot.com',
    androidClientId: '797974287154-5l81f0mmar5dmft60livfdemavl9jrob.apps.googleusercontent.com',
    iosClientId: '797974287154-1uccn3cmcjajm3opmvl91h30ff2li5eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppFullstack',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYpNZVcPd4_-JrhYOB31dZb26XcgPKT6Q',
    appId: '1:797974287154:ios:ca2928bd15bc0bb6acbd2b',
    messagingSenderId: '797974287154',
    projectId: 'ecommerce-fbf9c',
    storageBucket: 'ecommerce-fbf9c.appspot.com',
    androidClientId: '797974287154-5l81f0mmar5dmft60livfdemavl9jrob.apps.googleusercontent.com',
    iosClientId: '797974287154-1uccn3cmcjajm3opmvl91h30ff2li5eh.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceAppFullstack',
  );

}